source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

target "MitDB" do
    pod 'MITDB', :path => '../'
    target "MitDBHandleTest" do
        pod 'MITDB', :path => '../'
    end
end
