source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

target "MitDB" do
#    pod 'YYModel'
#    pod 'FMDBMigrationManager'
#    pod 'FMDB/SQLCipher'
    pod 'MITDB', :path => '../'
    target "MitDBHandleTest" do
#        pod 'YYModel'
#        pod 'FMDBMigrationManager'
#        pod 'FMDB/SQLCipher'
        pod 'MITDB', :path => '../'
    end
end
